USE [master]
GO

/****** Object:  Database [TVSI_StockInfo]    Script Date: 11/15/2022 2:06:02 PM ******/
CREATE DATABASE [TVSI_StockInfo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Temp', FILENAME = N'E:\Database\TVSI_StockInfo.mdf' , SIZE = 711680KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Temp_log', FILENAME = N'E:\Database\TVSI_StockInfo_log.ldf' , SIZE = 1008000KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TVSI_StockInfo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TVSI_StockInfo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TVSI_StockInfo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TVSI_StockInfo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TVSI_StockInfo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TVSI_StockInfo] SET ARITHABORT OFF 
GO

ALTER DATABASE [TVSI_StockInfo] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TVSI_StockInfo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TVSI_StockInfo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TVSI_StockInfo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TVSI_StockInfo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TVSI_StockInfo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TVSI_StockInfo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TVSI_StockInfo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TVSI_StockInfo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TVSI_StockInfo] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TVSI_StockInfo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TVSI_StockInfo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TVSI_StockInfo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TVSI_StockInfo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TVSI_StockInfo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TVSI_StockInfo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TVSI_StockInfo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TVSI_StockInfo] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TVSI_StockInfo] SET  MULTI_USER 
GO

ALTER DATABASE [TVSI_StockInfo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TVSI_StockInfo] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TVSI_StockInfo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TVSI_StockInfo] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [TVSI_StockInfo] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TVSI_StockInfo] SET QUERY_STORE = OFF
GO

USE [TVSI_StockInfo]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [TVSI_StockInfo] SET  READ_WRITE 
GO

