USE [master]
GO

/****** Object:  Database [TVSI_COMMONDB]    Script Date: 11/15/2022 2:29:02 PM ******/
CREATE DATABASE [TVSI_COMMONDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TVSI_COMMONDB_Data', FILENAME = N'E:\Database\TVSI_COMMONDB\TVSI_COMMONDB.mdf' , SIZE = 11988672KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'TVSI_COMMONDB_1_Log', FILENAME = N'E:\Database\TVSI_COMMONDB\TVSI_COMMONDB_1_log.ldf' , SIZE = 32448KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%), 
( NAME = N'TVSI_COMMONDB_Log', FILENAME = N'E:\Database\TVSI_COMMONDB\TVSI_COMMONDB_log.ldf' , SIZE = 43264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TVSI_COMMONDB].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [TVSI_COMMONDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TVSI_COMMONDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TVSI_COMMONDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TVSI_COMMONDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TVSI_COMMONDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [TVSI_COMMONDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TVSI_COMMONDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TVSI_COMMONDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TVSI_COMMONDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TVSI_COMMONDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TVSI_COMMONDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TVSI_COMMONDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TVSI_COMMONDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TVSI_COMMONDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TVSI_COMMONDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TVSI_COMMONDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TVSI_COMMONDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TVSI_COMMONDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TVSI_COMMONDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TVSI_COMMONDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TVSI_COMMONDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TVSI_COMMONDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TVSI_COMMONDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TVSI_COMMONDB] SET  MULTI_USER 
GO

ALTER DATABASE [TVSI_COMMONDB] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO

ALTER DATABASE [TVSI_COMMONDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TVSI_COMMONDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TVSI_COMMONDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [TVSI_COMMONDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TVSI_COMMONDB] SET QUERY_STORE = OFF
GO

USE [TVSI_COMMONDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [TVSI_COMMONDB] SET  READ_WRITE 
GO

