USE [master]
GO

/****** Object:  Database [TVSI_WEBSITEDB]    Script Date: 11/15/2022 2:03:58 PM ******/
CREATE DATABASE [TVSI_WEBSITEDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TVSI_WEBSITEDB_Data', FILENAME = N'E:\Database\TVSI_WEBSITEDB\TVSI_WEBSITEDB.mdf' , SIZE = 1689600KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'TVSI_WEBSITEDB_1_Log', FILENAME = N'E:\Database\TVSI_WEBSITEDB\TVSI_WEBSITEDB_1_log.ldf' , SIZE = 65480KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%), 
( NAME = N'TVSI_WEBSITEDB_Log', FILENAME = N'E:\Database\TVSI_WEBSITEDB\TVSI_WEBSITEDB_log.ldf' , SIZE = 57664KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TVSI_WEBSITEDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TVSI_WEBSITEDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TVSI_WEBSITEDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TVSI_WEBSITEDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TVSI_WEBSITEDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TVSI_WEBSITEDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [TVSI_WEBSITEDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TVSI_WEBSITEDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TVSI_WEBSITEDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TVSI_WEBSITEDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TVSI_WEBSITEDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TVSI_WEBSITEDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TVSI_WEBSITEDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TVSI_WEBSITEDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TVSI_WEBSITEDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TVSI_WEBSITEDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TVSI_WEBSITEDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TVSI_WEBSITEDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TVSI_WEBSITEDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TVSI_WEBSITEDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TVSI_WEBSITEDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TVSI_WEBSITEDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TVSI_WEBSITEDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TVSI_WEBSITEDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TVSI_WEBSITEDB] SET  MULTI_USER 
GO

ALTER DATABASE [TVSI_WEBSITEDB] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO

ALTER DATABASE [TVSI_WEBSITEDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TVSI_WEBSITEDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TVSI_WEBSITEDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [TVSI_WEBSITEDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TVSI_WEBSITEDB] SET QUERY_STORE = OFF
GO

USE [TVSI_WEBSITEDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [TVSI_WEBSITEDB] SET  READ_WRITE 
GO

