USE [master]
GO

/****** Object:  Database [TVSI_SYSTEMNOTIFICATIONDB]    Script Date: 11/15/2022 2:02:55 PM ******/
CREATE DATABASE [TVSI_SYSTEMNOTIFICATIONDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TVSI_SYSTEMNOTIFICATIONDB_Data', FILENAME = N'E:\Database\TVSI_SYSTEMNOTIFICATIONDB\TVSI_SYSTEMNOTIFICATIONDB.mdf' , SIZE = 1499840KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'TVSI_SYSTEMNOTIFICATIONDB_Log', FILENAME = N'E:\Database\TVSI_SYSTEMNOTIFICATIONDB\TVSI_SYSTEMNOTIFICATIONDB_log.ldf' , SIZE = 1219712KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TVSI_SYSTEMNOTIFICATIONDB].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [TVSI_SYSTEMNOTIFICATIONDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TVSI_SYSTEMNOTIFICATIONDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TVSI_SYSTEMNOTIFICATIONDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TVSI_SYSTEMNOTIFICATIONDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TVSI_SYSTEMNOTIFICATIONDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [TVSI_SYSTEMNOTIFICATIONDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TVSI_SYSTEMNOTIFICATIONDB] SET AUTO_SHRINK ON 
GO

ALTER DATABASE [TVSI_SYSTEMNOTIFICATIONDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TVSI_SYSTEMNOTIFICATIONDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TVSI_SYSTEMNOTIFICATIONDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TVSI_SYSTEMNOTIFICATIONDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TVSI_SYSTEMNOTIFICATIONDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TVSI_SYSTEMNOTIFICATIONDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TVSI_SYSTEMNOTIFICATIONDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TVSI_SYSTEMNOTIFICATIONDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TVSI_SYSTEMNOTIFICATIONDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TVSI_SYSTEMNOTIFICATIONDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TVSI_SYSTEMNOTIFICATIONDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TVSI_SYSTEMNOTIFICATIONDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TVSI_SYSTEMNOTIFICATIONDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TVSI_SYSTEMNOTIFICATIONDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TVSI_SYSTEMNOTIFICATIONDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TVSI_SYSTEMNOTIFICATIONDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TVSI_SYSTEMNOTIFICATIONDB] SET  MULTI_USER 
GO

ALTER DATABASE [TVSI_SYSTEMNOTIFICATIONDB] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO

ALTER DATABASE [TVSI_SYSTEMNOTIFICATIONDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TVSI_SYSTEMNOTIFICATIONDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TVSI_SYSTEMNOTIFICATIONDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [TVSI_SYSTEMNOTIFICATIONDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TVSI_SYSTEMNOTIFICATIONDB] SET QUERY_STORE = OFF
GO

USE [TVSI_SYSTEMNOTIFICATIONDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [TVSI_SYSTEMNOTIFICATIONDB] SET  READ_WRITE 
GO

